### ISSUE TITLE
EasyScheduler call shell “task instance not set host”

### ISSUE THREAD

**Issue by JesseYaoLi** [analysys/EasyScheduler#625] opened 2019-07-24 10:23 UTC
EasyScheduler调度shell
EasyScheduler scheduling shell

- Centos native shell dispatch knime, scheduling is normal.
    Configure the environment docker version:
    Shell script is normal: docker
    The data is correctly written to the target table

- EasyScheduler scheduling steps

1. Create a workflow
2. Go online and execute.
3. Running results and Log
The workflow always shows the startup, log information "task instance not set host"

[EasyScheduler scheduling shell.docx] (https://github.com/analysys/EasyScheduler/files/3426212/EasyScheduler.shell.docx)

---
- Centos 本机Shell调度knime，调度正常。
   配置环境docker版：
   Shell script 正常：docker
   数据正确的写入目标表

- EasyScheduler调度步骤

1.   创建工作流
2.   上线，执行。
3.    运行结果和Log 
工作流一直显示启动中，log信息“task instance not set host”

[EasyScheduler调度shell.docx](https://github.com/analysys/EasyScheduler/files/3426212/EasyScheduler.shell.docx)

**Comment by boandai** [comment] 2019-07-24 11:07
if worker server not execute this task , this log will show!

see worker server runtime log, find out why worker server not take task and execute task

**Comment by boandai** [comment] 2019-07-24 11:08
Duplicate of #393

**Closed** 2019-08-06 03:32 UTC
Labels: enhancement
