### ISSUE TITLE
Multi-machine deployment task cannot be executed, error message "task instance dose not set host"(多机部署任务无法执行，错误提示 “task instance dose not set host“)

### ISSUE THREAD

**Issue by leiruiqi** [analysys/EasyScheduler#393] opened 2019-05-29 01:29 UTC
Version 1.0.2
Deployment method: zip package installation
Error description: The task can be operated normally when the single machine is deployed, but the multi-machine deployment, the task can not be executed, check the log, prompt "task instance dose not set host"

---
版本1.0.2
部署方式：压缩包安装
错误描述：单机部署的时候能正常运营任务，但是多机器部署，任务不能执行，查看日志，提示 “task instance dose not set host“

**Comment by boandai** [comment] 2019-07-24 11:08
Duplicate of #625

**Comment by boandai** [comment] 2019-07-24 11:11
I'm really very sorry for not response for a long time! 
If have any problem with easyscheduler, please let us know, thank you!

**Comment by boandai** [comment] 2019-08-12 08:18
Duplicate of #625， close this issue for now

**Closed by boandai** 2019-08-12 08:18 UTC
Labels: enhancement, question
